version: '3'

# This docker-compose is for developer workflows, not for running in production.
services:
  test_runner:
    build:
      context: ../..
      dockerfile: tools/unit_test/Dockerfile
#    volumes:
#      # The container expects all mock data to be in /data
#      - ${DATASET_PATH}:/data
#    networks:
#      - kbase-dev
#    ports:
#      - 3333:3333
