---
name: Build and Push Up Main Branch Image
on:
    push:
        branches:
            - main
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out GitHub Repo
              uses: actions/checkout@v2
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            - uses: FranzDiebold/github-env-vars-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                  # hmm, try this.
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN_KBASE_UI_MOCK_SERVICES }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  pull: true
                  push: true
                  build-args: |
                      BUILD_CONFIG=ci
                      BUILD_DATE=${{ steps.date.outputs.date }}
                      VCS_REF=${{ github.sha }}
                      BRANCH=${{ github.ref }}
                      TAG=${{ github.ref }}
                  tags: ghcr.io/${{ github.repository_owner }}/kbase-ui-mock-services:main
