---
name: Build and Push Up Main Branch Image
on:
  push:
    branches:
      - 'feature-*'
      - 'fix-*'
      - main
  pull_request:
    branches:
      - main
  release:
    branches:
      - main
    types: [published]
  workflow_dispatch:
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out GitHub Repo
              uses: actions/checkout@v2

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

            - uses: FranzDiebold/github-env-vars-action@v2
            
            #
            # Create friendly image tags
            # Cases we handle:
            # - push to "main" - name "main"
            # - any activity in PR against "main" - name "pull_request-#""
            # - release created - name "release", tag "release-v#.#.#""
            #
            - name: Create friendly tag for push to main
              if: github.event_name == 'push'
              run: echo IMAGE_TAG_NAME=main >> $GITHUB_ENV
      
            - name: Create friendly tag for pull request
              if: github.event_name == 'pull_request'
              run: echo IMAGE_TAG_NAME=pull_request-${{github.event.pull_request.number}} >> $GITHUB_ENV
      
            - name: Create friendly tag for a release against main
              if: github.event_name == 'release'
              run: |
                echo IMAGE_TAG_NAME=release-${{ github.event.release.tag_name }} >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ secrets.GHCR_USERNAME }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  pull: true
                  push: true
                  build-args: |
                      BUILD_DATE=${{ steps.date.outputs.date }}
                      VCS_REF=${{ github.sha }}
                      BRANCH=${{ github.ref }}
                      TAG=${{ github.ref }}
                  tags: ghcr.io/${{ github.repository_owner }}/kbase-mock-services:${{ env.IMAGE_TAG_NAME }}
